# Generated by Django 5.2 on 2025-06-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_detection_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='detections/annotated/'),
        ),
    ]
