# Generated by Django 5.2 on 2025-06-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_detection_annotated_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
