# Generated by Django 5.2 on 2025-06-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_alter_detection_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
