# Generated by Django 5.2 on 2025-06-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_alter_detection_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('snapshot', models.ImageField(upload_to='snapshots/')),
                ('face_image', models.ImageField(upload_to='faces/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
